version: 2

models:
  - name: stg_btc 
    columns:
      - name: HASH_KEY
        tests:
          - unique
          - not_null

  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')

  - name: whale_alert
    latest_version: 2
    config:
      contract:
        enforced: true
    columns:
      - name: INVOCATION_ID
        data_type: string
      - name: output_address
        data_type: string
        data_tests:
          - assert_valid_btc_address
      - name: total_sent
        data_type: float
      - name: tx_count
        data_type: int
      - name: total_sent_usd
        data_type: float

    versions:
      - v: 1
        deprecation_date: 2026-01-01
        # ✅ removed invalid `enabled` key
      - v: 2
        # Breaking change: removed total_sent_usd
        columns:
          - include: all
            exclude: [total_sent_usd]

exposures:
  - name: btc_whale_alert_exposure
    label: BTC Whale Alert Dashboard
    type: dashboard
    maturity: high
    url: https://app.fabric.microsoft.com/groups/me/reports/887a1320-c597-4d1e-a085-2cef1290f1c4/128bccc15ec5ddab6ad6?experience=fabric-developer
    description: >
      Power BI (Microsoft Fabric) dashboard showing Bitcoin whale transactions, volumes, and related analytics derived from dbt model outputs.
    depends_on:
      - ref('whale_alert', v=2)
    owner:
      name: Shamika
