version: 2

sources:
  - name: BTC
    database: BTC
    schema: BTC_schema
    tables:
      - name: BTC
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 3
            period: hour
        loaded_at_field: BLOCK_TIMESTAMP

